[tool.poetry]
name = "carrier-owl"
version = "0.1.0"
description = ""
authors = ["hppRC <hpp.ricecake@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
wheel = "^0.40.0"
slackweb = "^1.0.5"
lxml = "^4.9.1"
pyyaml = "^5.3.1"
beautifulsoup4 = "^4.11.1"
selenium = "^3.141.0"
webdriver-manager = "^3.3.0"
arxiv = "^2.2.0"
slack_sdk = "^3.4.2"
pandas = "^1.3.4"
openpyxl = "^3.0.10"
xlrd = "^2.0.1"
holidays = "^0.13"
requests-oauthlib = "^1.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
