name: Carrier Owl

on:
  schedule:
    # github actions のデフォルトの time zone が UTC なので、日本時間 - 9時間 した値を書く
    - cron:  '00 4 * * 1,2,3,4,5'
  workflow_dispatch:
  
  push:
    branches:
      - test-send-to-slack

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run image
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.2.0

      - name: install dependencies
        run: poetry install
        
      - name: Run owl
        run:
          poetry run python src/carrier_owl.py
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEEPL_API_TOKEN: ${{ secrets.DEEPL_API_TOKEN }}
          SLACK_ID: ${{ secrets.SLACK_ID }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_BOT_ID: ${{ secrets.SLACK_BOT_ID }}
          SLACK_CHANNEL_ID_DEV: ${{ secrets.SLACK_CHANNEL_ID_DEV }}
          MENTION_URL: ${{secrets.MENTION_URL}}
#           SLACK_ID_ASTROPH_GA: ${{ secrets.SLACK_ID_ASTROPH_GA }}
#           SLACK_ID_ASTROPH_CO: ${{ secrets.SLACK_ID_ASTROPH_CO }}
#           SLACK_ID_ASTROPH_HE: ${{ secrets.SLACK_ID_ASTROPH_HE }}
#           SLACK_ID_ASTROPH_EP: ${{ secrets.SLACK_ID_ASTROPH_EP }}
#           SLACK_ID_ASTROPH_IM: ${{ secrets.SLACK_ID_ASTROPH_IM }}
#           SLACK_ID_ASTROPH_SR: ${{ secrets.SLACK_ID_ASTROPH_SR }}
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          TEXTRA_API_NAME: ${{ secrets.TEXTRA_API_NAME }}
          TEXTRA_API_KEY: ${{ secrets.TEXTRA_API_KEY }}
          TEXTRA_API_SECRET: ${{ secrets.TEXTRA_API_SECRET }}



